// Code generated by core. DO NOT EDIT (base registry, regenerated each run).
using System.IO;

namespace Table
{
	public class BaseTables
	{
		public BaseAffixTable Affix = new BaseAffixTable();
		public BaseClassTable Class = new BaseClassTable();
		public BaseExperienceTable Experience = new BaseExperienceTable();
		public BaseItemTable Item = new BaseItemTable();
		public BaseLevelTable Level = new BaseLevelTable();
		public BaseMissileTable Missile = new BaseMissileTable();
		public BaseMonsterTable Monster = new BaseMonsterTable();
		public BaseMonumodTable Monumod = new BaseMonumodTable();
		public BaseSkillTable Skill = new BaseSkillTable();
		public BaseStartItemTable StartItem = new BaseStartItemTable();
		public BaseTreasureclassTable Treasureclass = new BaseTreasureclassTable();

		// LoadAll 从 dir 加载全部 base 表（dir/<name>.tsv）。
		public void LoadAll(string dir)
		{
			Affix.Load(Path.Combine(dir, "Affix.tsv"));
			Class.Load(Path.Combine(dir, "Class.tsv"));
			Experience.Load(Path.Combine(dir, "Experience.tsv"));
			Item.Load(Path.Combine(dir, "Item.tsv"));
			Level.Load(Path.Combine(dir, "Level.tsv"));
			Missile.Load(Path.Combine(dir, "Missile.tsv"));
			Monster.Load(Path.Combine(dir, "Monster.tsv"));
			Monumod.Load(Path.Combine(dir, "Monumod.tsv"));
			Skill.Load(Path.Combine(dir, "Skill.tsv"));
			StartItem.Load(Path.Combine(dir, "StartItem.tsv"));
			Treasureclass.Load(Path.Combine(dir, "Treasureclass.tsv"));
		}
	}
}
