// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseItemRow 表 "item_c" 的一行（强类型）。
	public class BaseItemRow
	{
		public int Id; // 物品 id（本项目编号）
		public string Name; // 物品名（中文）
		public string Code; // 官方 code
		public string Source; // 来源官方表（weap/armo/misc）
		public string Type; // 物品大类（官方 type）
		public string Subtype; // 子类（官方 type2，空则取 wclass）
		public int GridW; // 背包占格宽（官方 invwidth）
		public int GridH; // 背包占格高（官方 invheight）
		public int LvlReq; // 使用等级需求（官方 levelreq）
		public int ItemLevel; // 物品等级 qlvl（官方 level）
		public int StrReq; // 力量需求（官方 reqstr）
		public int DexReq; // 敏捷需求（官方 reqdex）
		public int DmgMin; // 单手伤害下限（官方 mindam）
		public int DmgMax; // 单手伤害上限（官方 maxdam）
		public int Dmg2Min; // 双手伤害下限（官方 2handmindam）
		public int Dmg2Max; // 双手伤害上限（官方 2handmaxdam）
		public int StrBonus; // 力量伤害加成%（官方 Weapons.StrBonus；弓/弩为 0；非武器为 0）
		public int DexBonus; // 敏捷伤害加成%（官方 Weapons.DexBonus；弓/弩为 100；非武器为 0）
		public int MisMin; // 投掷伤害下限（官方 minmisdam）
		public int MisMax; // 投掷伤害上限（官方 maxmisdam）
		public int DefMin; // 防御下限（官方 minac）
		public int DefMax; // 防御上限（官方 maxac）
		public int Block; // 格挡率（官方 block）
		public int Price; // 基础价格（官方 cost）
		public int Stack; // 可堆叠（官方 stackable）
		public int MinStack; // 最小堆叠数（官方 minstack）
		public int MaxStack; // 最大堆叠数（官方 maxstack）
		public int TwoHanded; // 仅双手（官方 2handed）
		public int OneOrTwo; // 可单手可双手（官方 1or2handed）
		public int Speed; // 武器速度修正（官方 speed）
		public int Sockets; // 最大孔数（官方 gemsockets）
		public int BeltSlots; // 腰带可放药水数（官方 belt）
		public int Quest; // 是否任务物品（官方 quest）
	}

	// BaseItemTable 表 "item_c" 的只读容器（按主键索引）。
	public class BaseItemTable
	{
		private List<BaseItemRow> rows = new List<BaseItemRow>();
		private Dictionary<int, BaseItemRow> index = new Dictionary<int, BaseItemRow>();

		public BaseItemRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseItemRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseItemRow>();
			index = new Dictionary<int, BaseItemRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseItemRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.Code = TableParsers.Cell(rec, 2);
				row.Source = TableParsers.Cell(rec, 3);
				row.Type = TableParsers.Cell(rec, 4);
				row.Subtype = TableParsers.Cell(rec, 5);
				row.GridW = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.GridH = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.LvlReq = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.ItemLevel = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.StrReq = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.DexReq = TableParsers.ToInt(TableParsers.Cell(rec, 11));
				row.DmgMin = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.DmgMax = TableParsers.ToInt(TableParsers.Cell(rec, 13));
				row.Dmg2Min = TableParsers.ToInt(TableParsers.Cell(rec, 14));
				row.Dmg2Max = TableParsers.ToInt(TableParsers.Cell(rec, 15));
				row.StrBonus = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.DexBonus = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.MisMin = TableParsers.ToInt(TableParsers.Cell(rec, 18));
				row.MisMax = TableParsers.ToInt(TableParsers.Cell(rec, 19));
				row.DefMin = TableParsers.ToInt(TableParsers.Cell(rec, 20));
				row.DefMax = TableParsers.ToInt(TableParsers.Cell(rec, 21));
				row.Block = TableParsers.ToInt(TableParsers.Cell(rec, 22));
				row.Price = TableParsers.ToInt(TableParsers.Cell(rec, 23));
				row.Stack = TableParsers.ToInt(TableParsers.Cell(rec, 24));
				row.MinStack = TableParsers.ToInt(TableParsers.Cell(rec, 25));
				row.MaxStack = TableParsers.ToInt(TableParsers.Cell(rec, 26));
				row.TwoHanded = TableParsers.ToInt(TableParsers.Cell(rec, 27));
				row.OneOrTwo = TableParsers.ToInt(TableParsers.Cell(rec, 28));
				row.Speed = TableParsers.ToInt(TableParsers.Cell(rec, 29));
				row.Sockets = TableParsers.ToInt(TableParsers.Cell(rec, 30));
				row.BeltSlots = TableParsers.ToInt(TableParsers.Cell(rec, 31));
				row.Quest = TableParsers.ToInt(TableParsers.Cell(rec, 32));
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
