// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseMonsterRow 表 "monster_c" 的一行（强类型）。
	public class BaseMonsterRow
	{
		public int Id; // 怪物 id（1-8，本项目编号）
		public string Name; // 怪物名（中文）
		public string Code; // 官方 MonStats.Id
		public string NameStr; // 官方 NameStr（英文名）
		public string BaseId; // 官方 BaseId（同类基础怪）
		public int Level; // 换算所用等级（= 区域等级；三处区域均为 1）
		public int BaseLevel; // 官方 MonStats.Level（怪物等级基线，仅参考）
		public int MinGrp; // 刷怪最小成群数（官方 MinGrp）
		public int MaxGrp; // 刷怪最大成群数（官方 MaxGrp）
		public int Rarity; // 出现权重（官方 Rarity）
		public int Hp; // 生命（已按 MonLvl 倍率换算；= (hp_min+hp_max)/2）
		public int HpMin; // 生命下限（官方 minHP × MonLvl.HP/100）
		public int HpMax; // 生命上限（官方 maxHP × MonLvl.HP/100）
		public int Ac; // 防御（官方 AC × MonLvl.AC/100）
		public int Ar; // 命中（官方 A1TH × MonLvl.TH/100）
		public int DmgMin; // 近战伤害下限（官方 A1MinD × MonLvl.DM/100）
		public int DmgMax; // 近战伤害上限（官方 A1MaxD × MonLvl.DM/100）
		public int Exp; // 击杀经验（官方 Exp × MonLvl.XP/100）
		public string Ai; // AI 类型（官方 MonStats.AI）
		public float Speed; // 移动速度（官方 Velocity）
		public int Run; // 奔跑速度（官方 Run）
		public int ResPhys; // 物理抗性（官方 ResDm）
		public int ResMagic; // 魔法抗性（官方 ResMa）
		public int ResFire; // 火焰抗性（官方 ResFi）
		public int ResLight; // 闪电抗性（官方 ResLi）
		public int ResCold; // 冰冷抗性（官方 ResCo）
		public int ResPoison; // 毒素抗性（官方 ResPo）
		public string Sprite; // 动画代码（官方 MonStats.Code，DCC 文件名前缀）
		public int CorpseUsable; // 尸体可被选中/利用（官方 MonStats2.corpseSel）
		public int Revive; // 可被复活（官方 MonStats2.revive）
		public int Undead; // 亡灵（官方 lUndead|hUndead）
		public int Demon; // 恶魔（官方 demon）
		public int Flying; // 飞行（官方 flying）
		public string TreasureClass; // 掉落表（官方 TreasureClass1，指向 treasureclass_c）
	}

	// BaseMonsterTable 表 "monster_c" 的只读容器（按主键索引）。
	public class BaseMonsterTable
	{
		private List<BaseMonsterRow> rows = new List<BaseMonsterRow>();
		private Dictionary<int, BaseMonsterRow> index = new Dictionary<int, BaseMonsterRow>();

		public BaseMonsterRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseMonsterRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseMonsterRow>();
			index = new Dictionary<int, BaseMonsterRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseMonsterRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.Code = TableParsers.Cell(rec, 2);
				row.NameStr = TableParsers.Cell(rec, 3);
				row.BaseId = TableParsers.Cell(rec, 4);
				row.Level = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.BaseLevel = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.MinGrp = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.MaxGrp = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.Rarity = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.Hp = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.HpMin = TableParsers.ToInt(TableParsers.Cell(rec, 11));
				row.HpMax = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.Ac = TableParsers.ToInt(TableParsers.Cell(rec, 13));
				row.Ar = TableParsers.ToInt(TableParsers.Cell(rec, 14));
				row.DmgMin = TableParsers.ToInt(TableParsers.Cell(rec, 15));
				row.DmgMax = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.Exp = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.Ai = TableParsers.Cell(rec, 18);
				row.Speed = TableParsers.ToFloat(TableParsers.Cell(rec, 19));
				row.Run = TableParsers.ToInt(TableParsers.Cell(rec, 20));
				row.ResPhys = TableParsers.ToInt(TableParsers.Cell(rec, 21));
				row.ResMagic = TableParsers.ToInt(TableParsers.Cell(rec, 22));
				row.ResFire = TableParsers.ToInt(TableParsers.Cell(rec, 23));
				row.ResLight = TableParsers.ToInt(TableParsers.Cell(rec, 24));
				row.ResCold = TableParsers.ToInt(TableParsers.Cell(rec, 25));
				row.ResPoison = TableParsers.ToInt(TableParsers.Cell(rec, 26));
				row.Sprite = TableParsers.Cell(rec, 27);
				row.CorpseUsable = TableParsers.ToInt(TableParsers.Cell(rec, 28));
				row.Revive = TableParsers.ToInt(TableParsers.Cell(rec, 29));
				row.Undead = TableParsers.ToInt(TableParsers.Cell(rec, 30));
				row.Demon = TableParsers.ToInt(TableParsers.Cell(rec, 31));
				row.Flying = TableParsers.ToInt(TableParsers.Cell(rec, 32));
				row.TreasureClass = TableParsers.Cell(rec, 33);
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
