// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseMonumodRow 表 "monumod_c" 的一行（强类型）。
	public class BaseMonumodRow
	{
		public int Id; // 词缀 id（1-…，本项目编号）
		public string Name; // 词缀名（中文）
		public string Code; // 官方 MonUMod.uniquemod
		public int Kind; // 类型：0 = 冠军怪 / 1 = 精英怪（唯一怪）
		public int Version; // 官方 version（0 = 经典，100 = 资料片专属）
		public int ChampionChance; // 冠军怪出现几率%（官方 MonUMod.txt 常数 'champion chance'，全局）
		public float HpMul; // 生命倍率（1 + 官方常数 hp% / 100）
		public float DmgMul; // 伤害倍率（1 + 官方常数 dmg% / 100）
		public int TohitAdd; // 命中加成%（官方常数 +tohit%）
		public int ElemMinAdd; // 元素伤害下限加成%（官方常数 +elem min dmg%）
		public int ElemMaxAdd; // 元素伤害上限加成%（官方常数 +elem max dmg%）
		public float AcMul; // 护甲倍率（⚠️ 官方 MonUMod.txt 未定义该常数，占位 1.0）
		public int ResPhys; // 物理抗性加成%（⚠️ 官方未定义，占位 0）
		public int ResMagic; // 魔法抗性加成%（⚠️ 官方未定义，占位 0）
		public int ResFire; // 火焰抗性加成%（⚠️ 官方未定义，占位 0）
		public int ResLight; // 闪电抗性加成%（⚠️ 官方未定义，占位 0）
		public int ResCold; // 冰冷抗性加成%（⚠️ 官方未定义，占位 0）
		public int ResPoison; // 毒素抗性加成%（⚠️ 官方未定义，占位 0）
		public int Cpick; // 冠军怪抽取权重（官方 cpick）
		public int Upick; // 精英怪抽取权重（官方 upick）
		public string Constants; // 官方 constants 原文（审计用）
		public string Desc; // 官方 *constant desc 原文（审计用）
	}

	// BaseMonumodTable 表 "monumod_c" 的只读容器（按主键索引）。
	public class BaseMonumodTable
	{
		private List<BaseMonumodRow> rows = new List<BaseMonumodRow>();
		private Dictionary<int, BaseMonumodRow> index = new Dictionary<int, BaseMonumodRow>();

		public BaseMonumodRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseMonumodRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseMonumodRow>();
			index = new Dictionary<int, BaseMonumodRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseMonumodRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.Code = TableParsers.Cell(rec, 2);
				row.Kind = TableParsers.ToInt(TableParsers.Cell(rec, 3));
				row.Version = TableParsers.ToInt(TableParsers.Cell(rec, 4));
				row.ChampionChance = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.HpMul = TableParsers.ToFloat(TableParsers.Cell(rec, 6));
				row.DmgMul = TableParsers.ToFloat(TableParsers.Cell(rec, 7));
				row.TohitAdd = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.ElemMinAdd = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.ElemMaxAdd = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.AcMul = TableParsers.ToFloat(TableParsers.Cell(rec, 11));
				row.ResPhys = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.ResMagic = TableParsers.ToInt(TableParsers.Cell(rec, 13));
				row.ResFire = TableParsers.ToInt(TableParsers.Cell(rec, 14));
				row.ResLight = TableParsers.ToInt(TableParsers.Cell(rec, 15));
				row.ResCold = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.ResPoison = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.Cpick = TableParsers.ToInt(TableParsers.Cell(rec, 18));
				row.Upick = TableParsers.ToInt(TableParsers.Cell(rec, 19));
				row.Constants = TableParsers.Cell(rec, 20);
				row.Desc = TableParsers.Cell(rec, 21);
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
