// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseSkillRow 表 "skill_c" 的一行（强类型）。
	public class BaseSkillRow
	{
		public int Id; // 技能 id（1-150，本项目编号）
		public int Class; // 所属职业（指向 class_c.id）
		public int Tree; // 技能树（1-3，官方 SkillDesc.SkillPage）
		public string Name; // 技能名（中文）
		public string Code; // 官方 skills.skill
		public int OfficialId; // 官方 skills.Id
		public int ReqLevel; // 需求等级（官方 reqlevel）
		public int MaxLevel; // 最高等级（官方 maxlvl）
		public int ReqSkill; // 前置技能（指向 skill_c.id，0 = 无）
		public int SkillPoints; // 每级消耗技能点（官方 skpoints）
		public int ManaCost; // 基础法力消耗（官方 mana）
		public int ManaPerLvl; // 每级法力增量（官方 lvlmana）
		public int DmgMin; // **1 级**伤害下限（(MinDam+EMin) × 2^HitShift / 256，等级缩放见 *_lev* 列）
		public int DmgMax; // **1 级**伤害上限（(MaxDam+EMax) × 2^HitShift / 256，等级缩放见 *_lev* 列）
		public int PhysMin; // 物理伤害下限（官方 MinDam，未换算）
		public int PhysMax; // 物理伤害上限（官方 MaxDam，未换算）
		public int ElemMin; // 元素伤害下限（官方 EMin，未换算）
		public int ElemMax; // 元素伤害上限（官方 EMax，未换算）
		public int PhysMinLev1; // 物理下限每级增量 1~8 级（官方 MinLevDam1，未换算）
		public int PhysMinLev2; // 物理下限每级增量 9~16 级（官方 MinLevDam2）
		public int PhysMinLev3; // 物理下限每级增量 17~22 级（官方 MinLevDam3）
		public int PhysMinLev4; // 物理下限每级增量 23~28 级（官方 MinLevDam4）
		public int PhysMinLev5; // 物理下限每级增量 29+ 级（官方 MinLevDam5）
		public int PhysMaxLev1; // 物理上限每级增量 1~8 级（官方 MaxLevDam1）
		public int PhysMaxLev2; // 物理上限每级增量 9~16 级（官方 MaxLevDam2）
		public int PhysMaxLev3; // 物理上限每级增量 17~22 级（官方 MaxLevDam3）
		public int PhysMaxLev4; // 物理上限每级增量 23~28 级（官方 MaxLevDam4）
		public int PhysMaxLev5; // 物理上限每级增量 29+ 级（官方 MaxLevDam5）
		public int ElemMinLev1; // 元素下限每级增量 1~8 级（官方 EMinLev1）
		public int ElemMinLev2; // 元素下限每级增量 9~16 级（官方 EMinLev2）
		public int ElemMinLev3; // 元素下限每级增量 17~22 级（官方 EMinLev3）
		public int ElemMinLev4; // 元素下限每级增量 23~28 级（官方 EMinLev4）
		public int ElemMinLev5; // 元素下限每级增量 29+ 级（官方 EMinLev5）
		public int ElemMaxLev1; // 元素上限每级增量 1~8 级（官方 EMaxLev1）
		public int ElemMaxLev2; // 元素上限每级增量 9~16 级（官方 EMaxLev2）
		public int ElemMaxLev3; // 元素上限每级增量 17~22 级（官方 EMaxLev3）
		public int ElemMaxLev4; // 元素上限每级增量 23~28 级（官方 EMaxLev4）
		public int ElemMaxLev5; // 元素上限每级增量 29+ 级（官方 EMaxLev5）
		public int HitShift; // 伤害移位（官方 HitShift）
		public string DmgType; // 伤害类型（官方 EType：fire/cold/ltng/pois/mag，空 = 物理）
		public int Passive; // 是否被动技能（官方 passive）
		public string Missile; // 投射物（官方 srvmissile，空则取 cltmissile；指向 missile_c.code）
		public string Desc; // 技能说明（本项目按官方字段拼装）
	}

	// BaseSkillTable 表 "skill_c" 的只读容器（按主键索引）。
	public class BaseSkillTable
	{
		private List<BaseSkillRow> rows = new List<BaseSkillRow>();
		private Dictionary<int, BaseSkillRow> index = new Dictionary<int, BaseSkillRow>();

		public BaseSkillRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseSkillRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseSkillRow>();
			index = new Dictionary<int, BaseSkillRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseSkillRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Class = TableParsers.ToInt(TableParsers.Cell(rec, 1));
				row.Tree = TableParsers.ToInt(TableParsers.Cell(rec, 2));
				row.Name = TableParsers.Cell(rec, 3);
				row.Code = TableParsers.Cell(rec, 4);
				row.OfficialId = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.ReqLevel = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.MaxLevel = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.ReqSkill = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.SkillPoints = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.ManaCost = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.ManaPerLvl = TableParsers.ToInt(TableParsers.Cell(rec, 11));
				row.DmgMin = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.DmgMax = TableParsers.ToInt(TableParsers.Cell(rec, 13));
				row.PhysMin = TableParsers.ToInt(TableParsers.Cell(rec, 14));
				row.PhysMax = TableParsers.ToInt(TableParsers.Cell(rec, 15));
				row.ElemMin = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.ElemMax = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.PhysMinLev1 = TableParsers.ToInt(TableParsers.Cell(rec, 18));
				row.PhysMinLev2 = TableParsers.ToInt(TableParsers.Cell(rec, 19));
				row.PhysMinLev3 = TableParsers.ToInt(TableParsers.Cell(rec, 20));
				row.PhysMinLev4 = TableParsers.ToInt(TableParsers.Cell(rec, 21));
				row.PhysMinLev5 = TableParsers.ToInt(TableParsers.Cell(rec, 22));
				row.PhysMaxLev1 = TableParsers.ToInt(TableParsers.Cell(rec, 23));
				row.PhysMaxLev2 = TableParsers.ToInt(TableParsers.Cell(rec, 24));
				row.PhysMaxLev3 = TableParsers.ToInt(TableParsers.Cell(rec, 25));
				row.PhysMaxLev4 = TableParsers.ToInt(TableParsers.Cell(rec, 26));
				row.PhysMaxLev5 = TableParsers.ToInt(TableParsers.Cell(rec, 27));
				row.ElemMinLev1 = TableParsers.ToInt(TableParsers.Cell(rec, 28));
				row.ElemMinLev2 = TableParsers.ToInt(TableParsers.Cell(rec, 29));
				row.ElemMinLev3 = TableParsers.ToInt(TableParsers.Cell(rec, 30));
				row.ElemMinLev4 = TableParsers.ToInt(TableParsers.Cell(rec, 31));
				row.ElemMinLev5 = TableParsers.ToInt(TableParsers.Cell(rec, 32));
				row.ElemMaxLev1 = TableParsers.ToInt(TableParsers.Cell(rec, 33));
				row.ElemMaxLev2 = TableParsers.ToInt(TableParsers.Cell(rec, 34));
				row.ElemMaxLev3 = TableParsers.ToInt(TableParsers.Cell(rec, 35));
				row.ElemMaxLev4 = TableParsers.ToInt(TableParsers.Cell(rec, 36));
				row.ElemMaxLev5 = TableParsers.ToInt(TableParsers.Cell(rec, 37));
				row.HitShift = TableParsers.ToInt(TableParsers.Cell(rec, 38));
				row.DmgType = TableParsers.Cell(rec, 39);
				row.Passive = TableParsers.ToInt(TableParsers.Cell(rec, 40));
				row.Missile = TableParsers.Cell(rec, 41);
				row.Desc = TableParsers.Cell(rec, 42);
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
