// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseLevelRow 表 "level_c" 的一行（强类型）。
	public class BaseLevelRow
	{
		public int Id; // 区域 id（1-3，本项目编号）
		public string Name; // 区域名（中文）
		public string Code; // 官方 Levels.Name（Act 1 - Town / Wilderness 1 / Cave 1）
		public string LevelName; // 官方 Levels.LevelName（Rogue Encampment / Blood Moor / Den of Evil）
		public int LevelId; // 官方 Levels.Id
		public int Act; // 所属章节（官方 Act，0 基 ⇒ 0 = 第一幕）
		public int AreaLevel; // 区域等级（官方 MonLvl1）
		public int MonDensity; // 怪物密度（官方 MonDen，千分之几）
		public int MonUmin; // 冠军/精英怪下限（官方 MonUMin）
		public int MonUmax; // 冠军/精英怪上限（官方 MonUMax）
		public int NumMon; // 同时存在的怪物种类数（官方 NumMon）
		public int[] Monsters; // 该区域刷出的怪物 id 列表（指向 monster_c.id）
		public int SizeX; // 官方 SizeX
		public int SizeY; // 官方 SizeY
		public int SizeMin; // 生成尺寸下限（= min(SizeX, SizeY)）
		public int SizeMax; // 生成尺寸上限（= max(SizeX, SizeY)）
		public int Random; // 是否随机生成（官方 DrlgType == 2 为固定地形，其余为随机 ⇒ 1/0）
		public int DrlgType; // 官方 DrlgType（1 洞穴 / 2 固定 / 3 野外）
		public int IsInside; // 是否室内（官方 IsInside）
	}

	// BaseLevelTable 表 "level_c" 的只读容器（按主键索引）。
	public class BaseLevelTable
	{
		private List<BaseLevelRow> rows = new List<BaseLevelRow>();
		private Dictionary<int, BaseLevelRow> index = new Dictionary<int, BaseLevelRow>();

		public BaseLevelRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseLevelRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseLevelRow>();
			index = new Dictionary<int, BaseLevelRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseLevelRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.Code = TableParsers.Cell(rec, 2);
				row.LevelName = TableParsers.Cell(rec, 3);
				row.LevelId = TableParsers.ToInt(TableParsers.Cell(rec, 4));
				row.Act = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.AreaLevel = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.MonDensity = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.MonUmin = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.MonUmax = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.NumMon = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.Monsters = TableParsers.ParseSliceInt(TableParsers.Cell(rec, 11));
				row.SizeX = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.SizeY = TableParsers.ToInt(TableParsers.Cell(rec, 13));
				row.SizeMin = TableParsers.ToInt(TableParsers.Cell(rec, 14));
				row.SizeMax = TableParsers.ToInt(TableParsers.Cell(rec, 15));
				row.Random = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.DrlgType = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.IsInside = TableParsers.ToInt(TableParsers.Cell(rec, 18));
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
