// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseTreasureclassRow 表 "treasureclass_c" 的一行（强类型）。
	public class BaseTreasureclassRow
	{
		public string Name; // TC 名（官方 Treasure Class，主键）
		public int Group; // TC 组（官方 group）
		public int Level; // TC 等级（官方 level）
		public int Picks; // 抽取次数（官方 Picks）
		public int Nodrop; // 不掉落权重（官方 NoDrop）
		public string Drops; // 掉落项与权重，格式 item;prob|item;prob（官方 Item1..Item10 / Prob1..Prob10）
		public string NextTc; // 被引用的子 TC（官方 Item 里指向 TC 的项，; 分隔；指向物品的项不在此列）
		public int Unique; // 成色·唯一（官方 Unique）
		public int Set; // 成色·套装（官方 Set）
		public int Rare; // 成色·稀有（官方 Rare）
		public int Magic; // 成色·魔法（官方 Magic）
		public int IsAct1Start; // 是否属于 Act 1 起点 TC（1 = 闭包起点，0 = 被引用进来的子 TC）
	}

	// BaseTreasureclassTable 表 "treasureclass_c" 的只读容器（按主键索引）。
	public class BaseTreasureclassTable
	{
		private List<BaseTreasureclassRow> rows = new List<BaseTreasureclassRow>();
		private Dictionary<string, BaseTreasureclassRow> index = new Dictionary<string, BaseTreasureclassRow>();

		public BaseTreasureclassRow Get(string id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseTreasureclassRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseTreasureclassRow>();
			index = new Dictionary<string, BaseTreasureclassRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseTreasureclassRow();
				row.Name = TableParsers.Cell(rec, 0);
				row.Group = TableParsers.ToInt(TableParsers.Cell(rec, 1));
				row.Level = TableParsers.ToInt(TableParsers.Cell(rec, 2));
				row.Picks = TableParsers.ToInt(TableParsers.Cell(rec, 3));
				row.Nodrop = TableParsers.ToInt(TableParsers.Cell(rec, 4));
				row.Drops = TableParsers.Cell(rec, 5);
				row.NextTc = TableParsers.Cell(rec, 6);
				row.Unique = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.Set = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.Rare = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.Magic = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.IsAct1Start = TableParsers.ToInt(TableParsers.Cell(rec, 11));
				rows.Add(row);
				index[row.Name] = row;
			}
		}
	}
}
