// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseClassRow 表 "class_c" 的一行（强类型）。
	public class BaseClassRow
	{
		public int Id; // 职业 id（1-5）
		public string Name; // 职业名（中文）
		public string Code; // 官方 charstats.class
		public string SkillClass; // skills.txt 的 charclass 标识（ama/sor/nec/pal/bar）
		public int Str; // 初始力量
		public int Dex; // 初始敏捷
		public int Vit; // 初始体力
		public int Eng; // 初始精力（官方列名为 int）
		public int StatPerLvl; // 每级可分配属性点
		public float LifePerLvl; // 每级生命成长（官方 LifePerLevel，已 ÷4）
		public float ManaPerLvl; // 每级法力成长（官方 ManaPerLevel，已 ÷4）
		public float StamPerLvl; // 每级耐力成长（官方 StaminaPerLevel，已 ÷4）
		public float LifePerVit; // 每点体力=生命（官方 LifePerVitality，已 ÷4）
		public float ManaPerMag; // 每点精力=法力（官方 ManaPerMagic，已 ÷4）
		public float StamPerVit; // 每点体力=耐力（官方 StaminaPerVitality，已 ÷4）
		public int ToHitFactor; // 命中修正（官方 ToHitFactor）
		public int WalkVelocity; // 行走速度（官方 WalkVelocity）
		public int RunVelocity; // 奔跑速度（官方 RunVelocity）
		public string StartSkill; // 初始技能（官方 StartSkill，官方表里部分职业为空）
	}

	// BaseClassTable 表 "class_c" 的只读容器（按主键索引）。
	public class BaseClassTable
	{
		private List<BaseClassRow> rows = new List<BaseClassRow>();
		private Dictionary<int, BaseClassRow> index = new Dictionary<int, BaseClassRow>();

		public BaseClassRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseClassRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseClassRow>();
			index = new Dictionary<int, BaseClassRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseClassRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.Code = TableParsers.Cell(rec, 2);
				row.SkillClass = TableParsers.Cell(rec, 3);
				row.Str = TableParsers.ToInt(TableParsers.Cell(rec, 4));
				row.Dex = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.Vit = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.Eng = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.StatPerLvl = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.LifePerLvl = TableParsers.ToFloat(TableParsers.Cell(rec, 9));
				row.ManaPerLvl = TableParsers.ToFloat(TableParsers.Cell(rec, 10));
				row.StamPerLvl = TableParsers.ToFloat(TableParsers.Cell(rec, 11));
				row.LifePerVit = TableParsers.ToFloat(TableParsers.Cell(rec, 12));
				row.ManaPerMag = TableParsers.ToFloat(TableParsers.Cell(rec, 13));
				row.StamPerVit = TableParsers.ToFloat(TableParsers.Cell(rec, 14));
				row.ToHitFactor = TableParsers.ToInt(TableParsers.Cell(rec, 15));
				row.WalkVelocity = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.RunVelocity = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.StartSkill = TableParsers.Cell(rec, 18);
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
