// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseAffixRow 表 "affix_c" 的一行（强类型）。
	public class BaseAffixRow
	{
		public int Id; // 词缀 id（本项目编号）
		public string Name; // 官方词缀名（英文原名；中文待官方 localized .tbl 到位后复核）
		public string NameCn; // 中文说明（本项目按官方 mod 码 + 数值生成）
		public string Kind; // 类型：pre = 前缀 / suf = 后缀
		public int Lvl; // 词缀等级 alvl（官方 level）
		public int LvlReq; // 需求等级（官方 levelreq）
		public int Group; // 同组互斥（官方 group）
		public string Mod; // 属性码（官方 mod1code）
		public int Param; // 属性参数（官方 mod1param）
		public int Min; // 属性最小值（官方 mod1min）
		public int Max; // 属性最大值（官方 mod1max）
		public int Freq; // 出现频率（官方 frequency）
		public int ClassOnly; // 是否职业专属（官方 classspecific）
		public string Class; // 专属职业（官方 class）
		public string[] ItemTypes; // 可出现的物品类型（官方 itype1..itype7）
		public string[] Etypes; // 排除的物品类型（官方 etype1..etype3）
	}

	// BaseAffixTable 表 "affix_c" 的只读容器（按主键索引）。
	public class BaseAffixTable
	{
		private List<BaseAffixRow> rows = new List<BaseAffixRow>();
		private Dictionary<int, BaseAffixRow> index = new Dictionary<int, BaseAffixRow>();

		public BaseAffixRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseAffixRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseAffixRow>();
			index = new Dictionary<int, BaseAffixRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseAffixRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.NameCn = TableParsers.Cell(rec, 2);
				row.Kind = TableParsers.Cell(rec, 3);
				row.Lvl = TableParsers.ToInt(TableParsers.Cell(rec, 4));
				row.LvlReq = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.Group = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.Mod = TableParsers.Cell(rec, 7);
				row.Param = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.Min = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.Max = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.Freq = TableParsers.ToInt(TableParsers.Cell(rec, 11));
				row.ClassOnly = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.Class = TableParsers.Cell(rec, 13);
				row.ItemTypes = TableParsers.ParseSliceString(TableParsers.Cell(rec, 14));
				row.Etypes = TableParsers.ParseSliceString(TableParsers.Cell(rec, 15));
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
