// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseMissileRow 表 "missile_c" 的一行（强类型）。
	public class BaseMissileRow
	{
		public int Id; // 投射物 id（本项目编号）
		public string Name; // 投射物名（中文）
		public string Code; // 官方 Missiles.Missile
		public int OfficialId; // 官方 Missiles.Id
		public int Speed; // 飞行速度（官方 Vel）
		public int MaxVel; // 最大速度（官方 MaxVel）
		public int Accel; // 加速度（官方 Accel）
		public int Radius; // 碰撞半径（官方 Size）
		public int Range; // 射程（官方 Range）
		public int DmgMin; // 物理伤害下限（官方 MinDamage，常为空 ⇒ 0）
		public int DmgMax; // 物理伤害上限（官方 MaxDamage，常为空 ⇒ 0）
		public int ElemMin; // 元素伤害下限（官方 EMin，常为空 ⇒ 0）
		public int ElemMax; // 元素伤害上限（官方 Emax，常为空 ⇒ 0）
		public string DmgType; // 元素类型（官方 EType）
		public int Light; // 光照半径（官方 Light）
		public string CelFile; // 动画文件（官方 CelFile）
		public int CollideType; // 碰撞类型（官方 CollideType）
		public int NextHit; // 穿透后继续命中（官方 NextHit）
		public int NextDelay; // 重复命中间隔（官方 NextDelay）
		public string SubMissile; // 子投射物（官方 SubMissile1）
		public string UsedBy; // 引用来源（审计用）
	}

	// BaseMissileTable 表 "missile_c" 的只读容器（按主键索引）。
	public class BaseMissileTable
	{
		private List<BaseMissileRow> rows = new List<BaseMissileRow>();
		private Dictionary<int, BaseMissileRow> index = new Dictionary<int, BaseMissileRow>();

		public BaseMissileRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseMissileRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseMissileRow>();
			index = new Dictionary<int, BaseMissileRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseMissileRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Name = TableParsers.Cell(rec, 1);
				row.Code = TableParsers.Cell(rec, 2);
				row.OfficialId = TableParsers.ToInt(TableParsers.Cell(rec, 3));
				row.Speed = TableParsers.ToInt(TableParsers.Cell(rec, 4));
				row.MaxVel = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.Accel = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				row.Radius = TableParsers.ToInt(TableParsers.Cell(rec, 7));
				row.Range = TableParsers.ToInt(TableParsers.Cell(rec, 8));
				row.DmgMin = TableParsers.ToInt(TableParsers.Cell(rec, 9));
				row.DmgMax = TableParsers.ToInt(TableParsers.Cell(rec, 10));
				row.ElemMin = TableParsers.ToInt(TableParsers.Cell(rec, 11));
				row.ElemMax = TableParsers.ToInt(TableParsers.Cell(rec, 12));
				row.DmgType = TableParsers.Cell(rec, 13);
				row.Light = TableParsers.ToInt(TableParsers.Cell(rec, 14));
				row.CelFile = TableParsers.Cell(rec, 15);
				row.CollideType = TableParsers.ToInt(TableParsers.Cell(rec, 16));
				row.NextHit = TableParsers.ToInt(TableParsers.Cell(rec, 17));
				row.NextDelay = TableParsers.ToInt(TableParsers.Cell(rec, 18));
				row.SubMissile = TableParsers.Cell(rec, 19);
				row.UsedBy = TableParsers.Cell(rec, 20);
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
