// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseExperienceRow 表 "experience_c" 的一行（强类型）。
	public class BaseExperienceRow
	{
		public int Level; // 等级（1-99）
		public long Exp; // 升到该级所需累计经验（官方 experience.txt；8 职业同值）
		public int ExpRatio; // 官方 ExpRatio（经验获得比率）
	}

	// BaseExperienceTable 表 "experience_c" 的只读容器（按主键索引）。
	public class BaseExperienceTable
	{
		private List<BaseExperienceRow> rows = new List<BaseExperienceRow>();
		private Dictionary<int, BaseExperienceRow> index = new Dictionary<int, BaseExperienceRow>();

		public BaseExperienceRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseExperienceRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseExperienceRow>();
			index = new Dictionary<int, BaseExperienceRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseExperienceRow();
				row.Level = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Exp = TableParsers.ToLong(TableParsers.Cell(rec, 1));
				row.ExpRatio = TableParsers.ToInt(TableParsers.Cell(rec, 2));
				rows.Add(row);
				index[row.Level] = row;
			}
		}
	}
}
