// Code generated by core. DO NOT EDIT (base, regenerated each run).
using System;
using System.Collections.Generic;
using System.IO;

namespace Table
{
	// BaseStartItemRow 表 "start_item_c" 的一行（强类型）。
	public class BaseStartItemRow
	{
		public int Id; // 行 id（本项目编号 1..N）
		public int Class; // 职业 id（指向 class_c.id）
		public int SlotIndex; // 官方 item 序号 1..10（对应官方列 itemN / itemNloc / itemNcount）
		public string Code; // 物品 code（指向 item_c.code；官方空位 '0' 已剔除）
		public string Loc; // 官方 itemNloc 原文（rarm/larm/head/torso/glov/boot/belt/neck/ring；空 = 未装备 ⇒ 进背包）
		public int Count; // 官方 itemNcount（数量）
		public int SrcLine; // 出处：官方 charstats.txt 的行号（1 基，含表头行）
	}

	// BaseStartItemTable 表 "start_item_c" 的只读容器（按主键索引）。
	public class BaseStartItemTable
	{
		private List<BaseStartItemRow> rows = new List<BaseStartItemRow>();
		private Dictionary<int, BaseStartItemRow> index = new Dictionary<int, BaseStartItemRow>();

		public BaseStartItemRow Get(int id) => index.ContainsKey(id) ? index[id] : null;
		public int Count => rows.Count;
		public List<BaseStartItemRow> All() => rows;

		// Load 从 tsv 加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
		public void Load(string path)
		{
			var lines = File.ReadAllLines(path);
			if (lines.Length < 1) return;
			rows = new List<BaseStartItemRow>();
			index = new Dictionary<int, BaseStartItemRow>();
			for (int li = 1; li < lines.Length; li++)
			{
				if (string.IsNullOrEmpty(lines[li])) continue;
				var rec = lines[li].Split('\t');
				var row = new BaseStartItemRow();
				row.Id = TableParsers.ToInt(TableParsers.Cell(rec, 0));
				row.Class = TableParsers.ToInt(TableParsers.Cell(rec, 1));
				row.SlotIndex = TableParsers.ToInt(TableParsers.Cell(rec, 2));
				row.Code = TableParsers.Cell(rec, 3);
				row.Loc = TableParsers.Cell(rec, 4);
				row.Count = TableParsers.ToInt(TableParsers.Cell(rec, 5));
				row.SrcLine = TableParsers.ToInt(TableParsers.Cell(rec, 6));
				rows.Add(row);
				index[row.Id] = row;
			}
		}
	}
}
