// Code generated by core. DO NOT EDIT (上层 registry，每次运行重新生成)。
using System.IO;

namespace Table
{
	public class Tables
	{
		// Default 全局配置表单例。引擎加载后即为已加载实例，业务直接 Tables.Default.<表名>.Get(id)。
		public static Tables Default = new Tables();
		public AffixTable Affix = new AffixTable();
		public ClassTable Class = new ClassTable();
		public ExperienceTable Experience = new ExperienceTable();
		public ItemTable Item = new ItemTable();
		public LevelTable Level = new LevelTable();
		public MissileTable Missile = new MissileTable();
		public MonsterTable Monster = new MonsterTable();
		public MonumodTable Monumod = new MonumodTable();
		public SkillTable Skill = new SkillTable();
		public StartItemTable StartItem = new StartItemTable();
		public TreasureclassTable Treasureclass = new TreasureclassTable();

		// LoadAll 从 dir 加载全部业务表（dir/<name>.tsv），并触发各表钩子。
		public void LoadAll(string dir)
		{
			Affix.LoadWithHooks(Path.Combine(dir, "Affix.tsv"));
			Class.LoadWithHooks(Path.Combine(dir, "Class.tsv"));
			Experience.LoadWithHooks(Path.Combine(dir, "Experience.tsv"));
			Item.LoadWithHooks(Path.Combine(dir, "Item.tsv"));
			Level.LoadWithHooks(Path.Combine(dir, "Level.tsv"));
			Missile.LoadWithHooks(Path.Combine(dir, "Missile.tsv"));
			Monster.LoadWithHooks(Path.Combine(dir, "Monster.tsv"));
			Monumod.LoadWithHooks(Path.Combine(dir, "Monumod.tsv"));
			Skill.LoadWithHooks(Path.Combine(dir, "Skill.tsv"));
			StartItem.LoadWithHooks(Path.Combine(dir, "StartItem.tsv"));
			Treasureclass.LoadWithHooks(Path.Combine(dir, "Treasureclass.tsv"));
		}
	}
}
