# -*- coding: utf-8 -*-
"""本项目新增的中文显示名映射表（**官方 1.10f txt 只有英文名，中文名由本项目编写**）。

⚠️ 复核提示：官方 localized `.tbl`（如 `expansionstring.tbl` / `string.tbl` / `patchstring.tbl`）
到位后，这些中文名需与官方译名逐条复核；本文件即"待复核"清单的唯一来源。

键 = 官方 txt 里的英文标识（怪物 `Id` / 技能 `skill` / 物品 `code` / 区域 `LevelName` / 职业 `class`），
值 = 本项目使用的中文显示名。
"""

# ── 职业（charstats.class，经典 5 职业） ─────────────────────────────
CLASS_CN = {
    "Amazon": "亚马逊",
    "Sorceress": "女法师",
    "Necromancer": "亡灵法师",
    "Paladin": "圣骑士",
    "Barbarian": "野蛮人",
}

# ── 区域（Levels.LevelName） ────────────────────────────────────────
LEVEL_CN = {
    "Rogue Encampment": "罗格营地",
    "Blood Moor": "血腥荒野",
    "Den of Evil": "邪恶洞穴",
}

# ── 怪物（MonStats.Id） ─────────────────────────────────────────────
MONSTER_CN = {
    "fallen1": "堕落者",
    "fallenshaman1": "堕落萨满",
    "quillrat1": "尖刺鼠",
    "zombie1": "僵尸",
    "corruptrogue1": "堕落罗格",
    "foulcrow2": "血鹰",
    "brute1": "巨兽",
    "wraith1": "幽灵",
}

# ── 精英/冠军词缀（MonUMod.uniquemod） ──────────────────────────────
MONUMOD_CN = {
    "champion": "冠军",
    "ghostly": "幽魂",
    "fanatic": "狂热",
    "possessed": "附身",
    "berserk": "狂暴",
    "strong": "强壮",
    "fast": "迅捷",
    "curse": "诅咒",
    "resist": "魔法抵抗",
    "fire": "火焰强化",
    "lightning": "闪电强化",
    "cold": "冰冷强化",
    "poisonhit": "剧毒攻击",
    "manahit": "法力燃烧",
    "teleport": "传送",
    "spectralhit": "幽灵一击",
    "stoneskin": "石肤",
    "multishot": "多重射击",
    "aura": "圣光加持",
}

# ── 投射物（Missiles.Missile） ──────────────────────────────────────
MISSILE_CN = {
    "arrow": "箭矢",
    "firearrow": "火焰箭",
    "coldarrow": "寒冰箭",
    "magicarrow": "魔法箭",
    "explodingarrow": "爆裂箭",
    "explodingarrowexp": "爆裂箭爆炸",
    "icearrow": "冰箭",
    "freezingarrow": "冻结之箭",
    "immolationarrow": "献祭之箭",
    "guidedarrow": "导引箭",
    "multipleshotarrow": "多重箭",
    "multipleshotbolt": "多重弩箭",
    "strafearrow": "扫射箭",
    "strafebolt": "扫射弩箭",
    "firebolt": "火弹",
    "icebolt": "冰弹",
    "iceblast": "冰爆",
    "glacialspike": "冰川尖刺",
    "frostnova": "霜之新星",
    "frozenorb": "冰霜宝珠",
    "chargedbolt": "充能弹",
    "lightningbolt": "闪电",
    "lightningjavelin": "闪电标枪",
    "lightningstrike": "闪电击",
    "lightningfury": "闪电之怒",
    "chainlightning": "连锁闪电",
    "nova": "新星",
    "fireball": "火球",
    "firewall": "火墙",
    "firewallmaker": "火墙生成器",
    "firemedium": "中号火焰",
    "firesmall": "小号火焰",
    "infernoflame1": "炼狱火焰 1",
    "infernoflame2": "炼狱火焰 2",
    "blaze": "火焰之径",
    "meteorcenter": "陨石中心",
    "teeth": "牙",
    "bonespear": "骨矛",
    "bonespirit": "骨魂",
    "bonecast": "白骨施法",
    "bonewallmaker": "骨墙生成器",
    "corpseexplosion": "尸爆",
    "poisoncorpseexplosion": "剧毒尸爆",
    "poisonexplosioncloud": "毒爆云",
    "poisonnova": "剧毒新星",
    "poisonjav": "毒标枪",
    "plaguejavelin": "瘟疫标枪",
    "spike1": "尖刺",
    "blessedhammer": "祝福之锤",
    "holybolt": "圣光弹",
    "fistoftheheavensdelay": "天堂之拳延迟",
    "sanctuarybolt": "庇护所光弹",
    "redemption": "救赎",
    "revivesmall": "复活（小）",
    "revivemedium": "复活（中）",
    "revivelarge": "复活（大）",
    "curseamplifydamage": "诅咒·伤害加深",
    "curseattract": "诅咒·吸引",
    "cursecast": "诅咒施放",
    "curseconfuse": "诅咒·迷乱",
    "cursedecrepify": "诅咒·衰老",
    "cursedimvision": "诅咒·微暗灵视",
    "curseironmaiden": "诅咒·铁娘子",
    "curselowerresist": "诅咒·降低抵抗",
    "cursereversevampire": "诅咒·偷取生命",
    "curseterror": "诅咒·恐惧",
    "curseweaken": "诅咒·削弱",
    "howl": "咆哮",
    "shout": "吼叫",
    "battlecry": "战嗥",
    "battleorders": "战斗体制",
    "battlecommand": "战斗指挥",
    "warcry": "战吼",
    "grimwardsmallstart": "恐怖图腾（小）",
    "grimwardmediumstart": "恐怖图腾（中）",
    "grimwardlargestart": "恐怖图腾（大）",
    "leapknockback": "跳跃击退",
    "chargedstrikebolt": "充能击电弹",
    "chillingarmorbolt": "冰冷护甲弹",
    "thunderstorm1": "雷云风暴 1",
    "blood1": "血",
    "sparkle": "闪光",
    "redlightmissile": "红光",
    "greenlightmissile": "绿光",
}

# ── 技能（skills.skill）—— 5 职业 × 30 = 150（经典职业的技能，LoD 的技能不在此列） ──
SKILL_CN = {
    # 亚马逊 · 弓与弩
    "Magic Arrow": "魔法箭",
    "Fire Arrow": "火焰箭",
    "Cold Arrow": "寒冰箭",
    "Multiple Shot": "多重箭",
    "Exploding Arrow": "爆裂箭",
    "Ice Arrow": "冰箭",
    "Guided Arrow": "导引箭",
    "Strafe": "扫射",
    "Immolation Arrow": "献祭之箭",
    "Freezing Arrow": "冻结之箭",
    # 亚马逊 · 被动与魔法
    "Inner Sight": "内视",
    "Critical Strike": "致命一击",
    "Dodge": "闪避",
    "Slow Missiles": "缓速投射",
    "Avoid": "躲避",
    "Penetrate": "穿透",
    "Decoy": "诱饵",
    "Evade": "回避",
    "Valkyrie": "女武神",
    "Pierce": "穿刺",
    # 亚马逊 · 标枪与长矛
    "Jab": "戳刺",
    "Power Strike": "强力打击",
    "Poison Javelin": "毒标枪",
    "Lightning Bolt": "闪电球",
    "Impale": "刺穿",
    "Lightning Fury": "闪电之怒",
    "Charged Strike": "充能一击",
    "Plague Javelin": "瘟疫标枪",
    "Fend": "连击",
    "Lightning Strike": "闪电击",
    # 女法师 · 火焰
    "Fire Bolt": "火弹",
    "Warmth": "温暖",
    "Inferno": "炼狱之火",
    "Blaze": "火焰之径",
    "Fire Ball": "火球",
    "Fire Wall": "火墙",
    "Enchant": "附魔",
    "Meteor": "陨石",
    "Fire Mastery": "火焰精通",
    "Hydra": "多头蛇",
    # 女法师 · 闪电
    "Charged Bolt": "充能弹",
    "Static Field": "静电力场",
    "Telekinesis": "心灵传动",
    "Nova": "新星",
    "Lightning": "闪电",
    "Chain Lightning": "连锁闪电",
    "Teleport": "传送",
    "Thunder Storm": "雷云风暴",
    "Energy Shield": "能量护盾",
    "Lightning Mastery": "闪电精通",
    # 女法师 · 冰冷
    "Ice Bolt": "冰弹",
    "Frozen Armor": "冻结护甲",
    "Frost Nova": "霜之新星",
    "Ice Blast": "冰爆",
    "Shiver Armor": "寒颤护甲",
    "Glacial Spike": "冰川尖刺",
    "Blizzard": "暴风雪",
    "Chilling Armor": "冰冷护甲",
    "Frozen Orb": "冰霜宝珠",
    "Cold Mastery": "冰冷精通",
    # 亡灵法师 · 诅咒
    "Amplify Damage": "伤害加深",
    "Dim Vision": "微暗灵视",
    "Weaken": "削弱",
    "Iron Maiden": "铁娘子",
    "Terror": "恐惧",
    "Confuse": "迷乱",
    "Life Tap": "偷取生命",
    "Attract": "吸引",
    "Decrepify": "衰老",
    "Lower Resist": "降低抵抗",
    # 亡灵法师 · 毒素与白骨
    "Teeth": "牙",
    "Bone Armor": "白骨护甲",
    "Poison Dagger": "淬毒匕首",
    "Corpse Explosion": "尸爆",
    "Bone Wall": "骨墙",
    "Poison Explosion": "剧毒爆裂",
    "Bone Spear": "骨矛",
    "Bone Prison": "白骨囚牢",
    "Poison Nova": "剧毒新星",
    "Bone Spirit": "骨魂",
    # 亡灵法师 · 召唤
    "Raise Skeleton": "召唤骷髅",
    "Skeleton Mastery": "骷髅精通",
    "Golem Mastery": "石魔精通",
    "Raise Skeletal Mage": "召唤骷髅法师",
    "Clay Golem": "黏土石魔",
    "BloodGolem": "鲜血石魔",
    "IronGolem": "钢铁石魔",
    "Summon Resist": "召唤抵抗",
    "FireGolem": "火焰石魔",
    "Revive": "复活",
    # 圣骑士 · 战斗技能
    "Sacrifice": "牺牲",
    "Smite": "重击",
    "Holy Bolt": "圣光弹",
    "Zeal": "热诚",
    "Charge": "冲锋",
    "Vengeance": "复仇",
    "Blessed Hammer": "祝福之锤",
    "Conversion": "转化",
    "Holy Shield": "圣盾",
    "Fist of the Heavens": "天堂之拳",
    # 圣骑士 · 攻击灵气
    "Might": "力量",
    "Holy Fire": "圣火",
    "Thorns": "荆棘",
    "Blessed Aim": "祝福瞄准",
    "Concentration": "专注",
    "Holy Freeze": "圣冰",
    "Holy Shock": "圣光",
    "Sanctuary": "庇护所",
    "Fanaticism": "狂热",
    "Conviction": "审判",
    # 圣骑士 · 防御灵气
    "Prayer": "祈祷",
    "Resist Fire": "抗火",
    "Defiance": "反抗",
    "Resist Cold": "抗寒",
    "Cleansing": "净化",
    "Resist Lightning": "抗电",
    "Vigor": "精力",
    "Meditation": "冥想",
    "Redemption": "救赎",
    "Salvation": "救世",
    # 野蛮人 · 战斗精通
    "Bash": "重击",
    "Leap": "跳跃",
    "Double Swing": "双手挥舞",
    "Stun": "击晕",
    "Double Throw": "双手投掷",
    "Leap Attack": "跳跃攻击",
    "Concentrate": "集中",
    "Frenzy": "狂乱",
    "Whirlwind": "旋风暴",
    "Berserk": "狂暴",
    # 野蛮人 · 战斗体制
    "Howl": "咆哮",
    "Find Potion": "寻找药水",
    "Taunt": "嘲讽",
    "Shout": "吼叫",
    "Find Item": "寻找物品",
    "Battle Cry": "战嗥",
    "Battle Orders": "战斗体制",
    "Grim Ward": "恐怖图腾",
    "War Cry": "战吼",
    "Battle Command": "战斗指挥",
    # 野蛮人 · 战斗专家
    "Sword Mastery": "剑精通",
    # 官方代码与常见译名不一致的几条（以官方 skills.skill 为准）
    "Dopplezon": "诱饵",
    "Axe Mastery": "斧精通",
    "Mace Mastery": "锤精通",
    "Pole Arm Mastery": "长柄武器精通",
    "Throwing Mastery": "投掷精通",
    "Spear Mastery": "长矛精通",
    "Increased Stamina": "增加耐力",
    "Iron Skin": "铁皮",
    "Increased Speed": "提升速度",
    "Natural Resistance": "天然抗性",
}

# ── 物品（Weapons/Armor/Misc 的官方 code）──────────────────────────────
ITEM_CN = {
    # 武器 · 斧
    "hax": "手斧", "axe": "斧", "lax": "大斧", "bax": "阔斧",
    # 武器 · 法杖 / 木棒 / 锤
    "wnd": "法杖", "ywn": "紫杉木法杖", "clb": "木棒", "scp": "权杖",
    "spc": "尖刺棒", "mac": "钉头锤",
    # 武器 · 剑
    "ssd": "短剑", "scm": "弯刀", "sbr": "军刀", "flc": "弯月刀",
    "crs": "水晶剑", "2hs": "双手剑",
    # 武器 · 匕首 / 投掷
    "dgr": "匕首", "dir": "德克短剑", "tkf": "投掷小刀", "tax": "投掷斧",
    # 武器 · 标枪 / 长矛 / 长柄
    "jav": "标枪", "pil": "重标枪", "spr": "长矛", "tri": "三叉戟",
    "bar": "长柄斧", "vou": "大砍刀",
    # 武器 · 法杖（长）/ 弓 / 弩
    "sst": "短杖", "lst": "长杖", "cst": "扭曲法杖",
    "sbw": "短弓", "hbw": "猎人之弓", "lbw": "长弓", "cbw": "复合弓",
    "lxb": "轻弩",
    # 武器 · 投掷药水 / 拳套 / 宝珠（资料片职业武器）
    "gpl": "窒息毒气药水", "opl": "爆裂药水",
    "axf": "短斧爪", "ktr": "拳刃", "wrb": "腕刃",
    "ob1": "鹰眼宝珠", "ob2": "神圣球体", "ob3": "烟晶球",
    # 防具 · 头盔
    "cap": "帽子", "skp": "骷髅帽", "hlm": "盔",
    "ba1": "颚骨帽", "ba2": "獠牙盔", "dr1": "狼头盔", "dr2": "鹰盔",
    # 防具 · 躯干
    "qui": "缝制甲", "lea": "皮甲", "hla": "硬皮甲", "stu": "镶钉皮甲",
    "rng": "锁环甲",
    # 防具 · 盾
    "buc": "圆盾", "sml": "小盾", "lrg": "大盾", "spk": "尖刺盾",
    "pa1": "小圆盾", "pa2": "圆盾（圣骑士）",
    # 防具 · 手套 / 靴 / 腰带
    "lgl": "轻型手套", "vgl": "重型手套", "mgl": "中护腕",
    "lbt": "皮靴", "vbt": "重型靴", "mbt": "锁甲靴",
    "lbl": "饰带", "vbl": "轻腰带", "mbl": "中腰带",
    # 防具 · 死灵法师头颅
    "ne1": "保存的头颅", "ne2": "丧尸头颅",
    # 杂物 · 药水
    "hpo": "治疗药水（经典）", "mpo": "法力药水（经典）",
    "hpf": "全满治疗药水", "mpf": "全满法力药水",
    "hp1": "微型治疗药水", "hp2": "轻型治疗药水", "hp3": "治疗药水",
    "hp4": "强力治疗药水", "hp5": "高级治疗药水",
    "mp1": "微型法力药水", "mp2": "轻型法力药水", "mp3": "法力药水",
    "mp4": "强力法力药水", "mp5": "高级法力药水",
    "rvs": "回复药水", "rvl": "全满回复药水",
    "vps": "耐力药水", "yps": "解毒药水", "wms": "解冻药水",
    # 杂物 · 书 / 卷轴 / 钥匙 / 金币
    "tbk": "回城之书", "ibk": "鉴定之书",
    "tsc": "回城卷轴", "isc": "鉴定卷轴",
    "key": "骷髅钥匙", "gld": "金币", "ear": "玩家之耳", "tch": "火把",
    # 杂物 · 箭矢 / 戒指 / 项链
    "aqv": "箭矢", "cqv": "弩箭", "amu": "项链", "rin": "戒指",
    # 杂物 · 宝石（碎裂 / 有裂痕 / 无暇 / 完美；宝石家族代码见官方 Misc.txt）
    "gcv": "碎裂的紫水晶", "gfv": "有裂痕的紫水晶", "gzv": "无暇的紫水晶",
    "gpv": "完美的紫水晶", "gsv": "紫水晶",
    "gcy": "碎裂的黄玉", "gfy": "有裂痕的黄玉", "gly": "无暇的黄玉",
    "gpy": "完美的黄玉", "gsy": "黄玉",
    "gcb": "碎裂的蓝宝石", "gfb": "有裂痕的蓝宝石", "glb": "无暇的蓝宝石",
    "gpb": "完美的蓝宝石", "gsb": "蓝宝石",
    "gcg": "碎裂的绿宝石", "gfg": "有裂痕的绿宝石", "glg": "无暇的绿宝石",
    "gpg": "完美的绿宝石", "gsg": "绿宝石",
    "gcr": "碎裂的红宝石", "gfr": "有裂痕的红宝石", "glr": "无暇的红宝石",
    "gpr": "完美的红宝石", "gsr": "红宝石",
    "gcw": "碎裂的钻石", "gfw": "有裂痕的钻石", "glw": "无暇的钻石",
    "gpw": "完美的钻石", "gsw": "钻石",
    "skc": "碎裂的头骨", "skf": "有裂痕的头骨", "skl": "无暇的头骨",
    "skz": "完美的头骨", "sku": "头骨",
}

# ── 通用（怪物 AI / 伤害类型） ──────────────────────────────────────
DAMAGE_TYPE_CN = {
    "": "物理",
    "phys": "物理",
    "fire": "火焰",
    "cold": "冰冷",
    "ltng": "闪电",
    "pois": "毒素",
    "mag": "魔法",
}

TREE_CN = {1: "第一系", 2: "第二系", 3: "第三系"}
